version: '3.8'
name: "url-shortener"

services:

  url-shortener:
    build: .
    image: localhost/url-shortener:latest
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      - MONGO_URI=mongodb://urlShortener:password@mongodb:27017/shortUrlsDb?w=majority

  mongodb:
    image: mongo:5.0.22
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db